let g:ale_completion_enabled = 1
set viminfo+=n~/.vim/viminfo

" ShortKey
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Theme 

set incsearch
set smartcase
set wildmenu

set noerrorbells
set novisualbell
set t_vb=
set tm=500

syntax enable

if $COLORTERM == 'gnome-terminal'
    set t_Co=256
endif

set smarttab
set ai
set si
set wrap
set virtualedit=all
set noendofline




